### PR TITLE
feat: Add zotero links

### PR DESCRIPTION
**Pull request by MaroLIACS**
Addition of recognizing zotero links to open linked bibliography entries. Works with {{zoteroSelectURI}} from obsidian-citation-plugin

### CODE REVIEW

**Comment by arnau** [comment]
Thanks @MaroLIACS for the contribution. Would you mind adding a bit of documentation in the README (autolinks section)? I'm not familiar with Zotero myself.

**Comment by MaroLIACS** [comment]
Sure thing! I think my README change should now also appear in the pull request? Not super familiar with GIT collaboration yet 😅

**Review by arnau — APPROVED** [review]
Thanks! I will merge as soon as I can

**Comment by arnau** [comment]
@MaroLIACS  Thanks again for the contribution! It will be released as part of version 0.11.0

**Pull request merged**
